spring:
    application:
        name: spring-cloud-zuul
server:
    port: 9001
zuul:
    routes:
        api-a:
            path: /login
            url: forward:/login
        api-b:
            path: /**
            service-id: spring-cloud-auth
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8000/eureka/

logging:
  level:
   com.maritree: debug